export const SPECS = {
  motor: [
    { label: 'Tipo', value: '4 tempos, SOHC, refrigerado a ar' },
    { label: 'Cilindrada', value: '249 cc' },
    { label: 'Diâmetro × Curso', value: '74,0 × 58,0 mm' },
    { label: 'Compressão', value: '9,80:1' },
    { label: 'Alimentação', value: 'Injeção eletrônica (4B43)' },
    { label: 'Combustível', value: 'Gasolina aditivada' },
    { label: 'Partida', value: 'Elétrica' },
  ],
  oleo: [
    { label: 'Tipo', value: 'SAE 20W-40 ou 20W-50' },
    { label: 'Especificação', value: 'API SL+ JASO MA' },
    { label: 'Marca', value: 'YAMALUBE (recomendado)' },
    { label: 'Sem troca do filtro', value: '1,35 L' },
    { label: 'Com troca do filtro', value: '1,45 L' },
    { label: 'Intervalo padrão', value: '5.000 km (manual)' },
    { label: 'Intervalo atual', value: '1.500 km (motor revisado)' },
  ],
  ignição: [
    { label: 'Vela', value: 'NGK DR8EA' },
    { label: 'Folga', value: '0,6 – 0,7 mm' },
    { label: 'Trocar a cada', value: '10.000 km' },
    { label: 'Verificar a cada', value: '5.000 km' },
    { label: 'Marcha lenta', value: '1.300 – 1.500 rpm' },
  ],
  pneus: [
    { label: 'Dianteiro', value: '110/70-17M/C 54S (com câmara)' },
    { label: 'Traseiro', value: '130/70-17M/C 62S (com câmara)' },
    { label: 'Pressão front (solo)', value: '2,00 kgf/cm² — 29 psi ✓' },
    { label: 'Pressão tras (solo)', value: '2,25 kgf/cm² — 33 psi ✓' },
    { label: 'Pressão front (carga)', value: '2,00 kgf/cm² — 29 psi' },
    { label: 'Pressão tras (carga)', value: '2,50 kgf/cm² — 36 psi' },
    { label: 'Original', value: 'Pirelli Sport Demon (motard/street)' },
    { label: 'Calibrar a cada', value: '7 dias ou sempre que possível' },
    { label: 'PSI motard', value: '29/33 psi correto — São tires de asfalto' },
  ],
  torques: [
    { item: 'Vela de ignição', kgfm: '1,75', nm: '17,5' },
    { item: 'Dreno do óleo', kgfm: '2,0', nm: '20' },
    { item: 'Tampa do filtro de óleo', kgfm: '1,0', nm: '10' },
    { item: 'Dreno óleo (sangria)', kgfm: '0,7', nm: '7' },
    { item: 'Eixo dianteiro', kgfm: '8,0', nm: '80' },
    { item: 'Eixo traseiro', kgfm: '8,5', nm: '85' },
    { item: 'Parafusos bauleto', kgfm: '2,3', nm: '23' },
  ],
  eletrica: [
    { label: 'Fluido de freio', value: 'DOT 4' },
    { label: 'Bateria', value: 'YTX7L-BS — 12V 6,0 Ah (VRLA)' },
    { label: 'Fusível principal', value: '20A' },
    { label: 'Farol', value: '12V 35/35W (halógena)' },
    { label: 'Tanque', value: '11,0 L (reserva 4,3 L)' },
    { label: 'Peso total', value: '144,0 kg (cheio)' },
    { label: 'Entre-eixos', value: '1.390 mm' },
    { label: 'Altura do assento', value: '870 mm' },
    { label: 'Transmissão', value: '5 marchas' },
  ],
  periodica: [
    { item: 'Corrente (folga/lubrif.)', km: 500, urgencia: 'alta' },
    { item: 'Óleo do motor', km: 1500, urgencia: 'alta' },
    { item: 'Filtro de óleo', km: 3000, urgencia: 'alta' },
    { item: 'Vela (verificar/limpar)', km: 5000, urgencia: 'media' },
    { item: 'Vela (substituir)', km: 10000, urgencia: 'alta' },
    { item: 'Filtro de ar (limpar)', km: 5000, urgencia: 'media' },
    { item: 'Embreagem (ajuste)', km: 5000, urgencia: 'media' },
    { item: 'Freios (nível/desgaste)', km: 5000, urgencia: 'alta' },
    { item: 'Pneus (pressão/sulco)', km: 500, urgencia: 'alta' },
    { item: 'Bateria (verificar)', km: 6000, urgencia: 'baixa' },
    { item: 'Fluido freio (trocar)', km: 0, urgencia: 'alta', anos: 2 },
    { item: 'Mangueiras freio', km: 0, urgencia: 'media', anos: 4 },
    { item: 'Válvulas (folga)', km: 5000, urgencia: 'alta', concessionaria: true },
  ],
};

export const DICAS = [
  {
    id: 'tclocs',
    title: 'T-CLOCS — Checklist pré-saída',
    emoji: '🏍️',
    urgencia: 'alta',
    items: [
      { label: 'T — Pneus e Rodas', desc: 'Pressão (29/33 psi frios), desgaste, raios, aros sem dano. Verificar semanalmente.' },
      { label: 'C — Comandos', desc: 'Manetes de freio/embreagem, cabo do acelerador (solto + firme), freio traseiro, tensão da corrente.' },
      { label: 'L — Luzes', desc: 'Farol, lanterna, pisca esquerdo/direito, freio (dianteiro + traseiro), buzina, painel aceso.' },
      { label: 'O — Óleo e Fluidos', desc: 'Nível de óleo (janelinha lateral, moto reta), fluido de freio (janelinha no reservatório), combustível.' },
      { label: 'C — Chassi', desc: 'Sem trincas na estrutura, parafusos visíveis apertados, amortecedores sem vazamento de óleo.' },
      { label: 'S — Side-stand', desc: 'Mola do cavalete lateral está funcionando, cavalete dobra completamente ao andar.' },
    ],
  },
  {
    id: 'corrente',
    title: 'Corrente de transmissão',
    emoji: '⛓️',
    urgencia: 'alta',
    items: [
      { label: 'Verificar a cada', desc: '500 km ou semanalmente. Moto no cavalete central, gire a roda traseira e verifique a folga na parte mais folgada.' },
      { label: 'Folga ideal', desc: '15 a 25 mm de folga vertical (aperte levemente e meça o movimento). Acima de 25mm = ajustar.' },
      { label: 'Lubrificar', desc: 'Spray de corrente (não use óleo de motor). Aplique no interior dos elos com a roda girando devagar. Após lavar sempre lubrificar.' },
      { label: 'Sinal de troca', desc: 'Corrente esticada demais (>25mm sem ajuste), elos enferrujados, corrente "dura" num ponto só, ou >20.000 km de uso.' },
      { label: 'IMPORTANTE', desc: 'Ao trocar a corrente, SEMPRE trocar pinhão + coroa juntos. Relação nova com componentes velhos desgasta 3× mais rápido.' },
    ],
  },
  {
    id: 'relacao',
    title: 'Relação — pinhão e coroa',
    emoji: '⚙️',
    urgencia: 'media',
    items: [
      { label: 'O que é', desc: 'Pinhão = engrenagem pequena na saída do motor. Coroa = engrenagem grande na roda traseira. A corrente conecta os dois.' },
      { label: 'XTZ 250X padrão', desc: 'Pinhão 14 dentes, coroa 45 dentes. Relação 1:3,21.' },
      { label: 'Inspecionar', desc: 'Junto com a corrente. Dentes devem ser retos/quadrados. Dentes em gancho, onda ou ponta = trocar.' },
      { label: 'Vida útil', desc: 'Geralmente 2 correntes por relação, ou ~30.000-40.000 km se bem mantida.' },
      { label: 'Custo', desc: 'Sempre orçar o kit completo (corrente+pinhão+coroa). Trocar separado é desperdício de dinheiro e peça nova.' },
    ],
  },
  {
    id: 'pneus',
    title: 'Pneus — calibragem e desgaste',
    emoji: '🔵',
    urgencia: 'alta',
    items: [
      { label: 'Pressão correta', desc: 'Dianteiro: 29 psi | Traseiro: 33 psi (solo). Com garupa/carga: traseiro 36 psi. Esses valores são corretos para os pneus motard/street da XTZ.' },
      { label: 'Quando calibrar', desc: 'SEMPRE com pneu frio — moto parada há 3h+ ou rodada menos de 1,5 km. Pneu quente apresenta até 4 psi a mais.' },
      { label: 'Frequência', desc: 'Semanalmente ou antes de qualquer saída longa. Pneu perde ~1 psi por mês naturalmente.' },
      { label: 'TWI — indicador de desgaste', desc: 'Procure as setas ou triângulos nas laterais do pneu. Quando a borracha chega no nível das marcas no sulco central = trocar IMEDIATAMENTE.' },
      { label: 'PSI baixo = perigo', desc: 'Pneu murcho esquenta, desgasta lateralmente e pode soltar do aro (câmara). Nunca andar abaixo de 25 psi.' },
    ],
  },
  {
    id: 'freios',
    title: 'Freios — pastilhas e fluido',
    emoji: '🔴',
    urgencia: 'alta',
    items: [
      { label: 'Pastilhas', desc: 'Mínimo 1 mm de material. Se dá pra ver o metal base ou ouvir rangido metálico = trocar AGORA. Não esperar acabar completamente.' },
      { label: 'Fluido DOT4', desc: 'Verificar nível na janelinha do reservatório a cada 2 semanas. Entre MAX e MIN. DOT4 não pode ser misturado com DOT3.' },
      { label: 'Trocar fluido', desc: 'A cada 2 anos ou 20.000 km, mesmo sem parecer sujo. O fluido absorve umidade do ar e perde eficiência com o tempo.' },
      { label: 'Disco', desc: 'Sem ranhuras profundas, empenamento ou corrosão excessiva. Disco com ranhuras afunda as pastilhas mais rápido.' },
      { label: 'Freio traseiro', desc: 'Pinça revisada na última manutenção (07/2026). Verificar vazamento a cada saída nos primeiros 500 km.' },
    ],
  },
  {
    id: 'oleo',
    title: 'Óleo do motor — como verificar',
    emoji: '🛢️',
    urgencia: 'alta',
    items: [
      { label: 'Como verificar', desc: 'Moto na vertical em superfície plana (NÃO no cavalete lateral). Ligue por 2-3 min, desligue, espere 5 min. Verifique a janelinha lateral.' },
      { label: 'Nível ideal', desc: 'Entre as marcas L (mín) e H (máx) da janelinha. Abaixo do L = completar imediatamente.' },
      { label: 'Quantidade', desc: '1,35 L sem trocar filtro | 1,45 L com filtro novo. YAMALUBE 20W-50 (API SL / JASO MA).' },
      { label: 'Frequência de verificação', desc: 'Mensal ou a cada 500 km. Motor revisado pode consumir um pouco mais de óleo nos primeiros meses.' },
      { label: 'Sinais de deterioração', desc: 'Óleo muito escuro e espesso antes do intervalo = trocar logo. Óleo com aparência de café com leite = água no motor (ir à oficina).' },
    ],
  },
  {
    id: 'filtro-ar',
    title: 'Filtro de ar',
    emoji: '💨',
    urgencia: 'media',
    items: [
      { label: 'Limpar a cada', desc: '5.000 km em asfalto. 2.000 km em terra/lama/poeira. Motor sente falta de ar — fica sem força e consome mais.' },
      { label: 'Como limpar', desc: 'Ar comprimido de DENTRO para fora (nunca de fora pra dentro). Não usar água. Não usar pano com pressão.' },
      { label: 'Quando trocar', desc: 'Se estiver rasgado, com buracos, ou após ~20.000 km de uso mesmo limpo.' },
      { label: 'Atenção', desc: 'Conduíte do filtro de ar trocado na última manutenção (07/2026). Verificar conexões nas primeiras 1.000 km.' },
    ],
  },
  {
    id: 'bateria',
    title: 'Bateria',
    emoji: '🔋',
    urgencia: 'baixa',
    items: [
      { label: 'Tipo', desc: 'YTX7L-BS — 12V 6Ah VRLA (selada). Não precisa de água. Não abrir.' },
      { label: 'Terminais oxidados', desc: 'Pó branco/verde nos terminais? Desconecte (negativo primeiro), limpe com escova de dentes + bicarbonato de sódio + água, seque bem, reconecte.' },
      { label: 'Moto parada', desc: 'Mais de 15 dias sem usar? Desconecte o cabo negativo. Mais de 30 dias = carregue a bateria (carregador de moto, nunca de carro).' },
      { label: 'Sem partida', desc: 'Verifique: fusível de 20A (sob o banco), chave correta, interruptores de parada. Clique único ao ligar = bateria fraca.' },
      { label: 'Vida útil', desc: '2 a 4 anos. Se após carregar não segura carga = trocar.' },
    ],
  },
  {
    id: 'consumo',
    title: 'Consumo e abastecimento',
    emoji: '⛽',
    urgencia: 'baixa',
    items: [
      { label: 'Reserva', desc: 'Tanque: 11 L total. A luz de reserva acende com ~1,5-2 L restantes. Reserve ao menos 4 L (4,3 L de reserva no manual).' },
      { label: 'Consumo típico', desc: 'XTZ 250X: 25-35 km/L. Andando mais na cidade: ~25 km/L. Estrada em velocidade moderada: ~33 km/L.' },
      { label: 'Abastecer completo', desc: 'Sempre abastecimento cheio para calcular consumo real pelo Trip2. Anotar km no app após cada abastecimento.' },
      { label: 'Combustível', desc: 'Gasolina comum ou aditivada. NÃO use etanol puro — motor injecionado pode ter problemas a frio.' },
      { label: 'Trip1 e Trip2', desc: 'Trip1 = conta km até trocar óleo (zere a cada troca). Trip2 = consumo por tanque (zere a cada abastecimento cheio).' },
    ],
  },
];
